name: Ruff

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    name: Run Ruff checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ruff
        run: pip install --upgrade pip ruff

      - name: Show Ruff version
        run: ruff --version

      - name: Check formatting
        run: ruff format --check .

      - name: Lint with Ruff
        run: ruff check .


